### ISSUE TITLE
Webpack output libraryTarget "this"

### ISSUE THREAD

**Issue by aweber1** [pauldotknopf/JavaScriptViewEngine.Samples#2]
First, great library, thanks!

This isn't really an issue, more a bit of info that I wanted to pass along to anyone else using these samples as a starting point or reference (same goes for https://github.com/pauldotknopf/react-aspnet-boilerplate).

I was trying to port an existing webpack config and React app into the JavaScriptViewEngine.MVC5 sample and just could not get the webpack bundle to run. After a couple days of troubleshooting various things, I finally stumbled across the fact that my webpack output file was slightly different than the output file from the `Sample.MvcCore1.ReactWebpackSass` project. In comparing webpack configs, I noticed the `output.libraryTarget` definition in the `Sample.MvcCore1.ReactWebpackSass/webpack.config.js` file was set to `"this"` where my existing webpack config was just using the default. After changing that setting and repacking, everything worked!

Hope this saves someone else some time. Happy to submit a PR if this belongs in a readme or doc somewhere, just wasn't sure where you might want it.

**Comment by pauldotknopf** [comment]
Interesting. I've only every had it work using "this".

Do you mind sending me a sample project where "this" breaks things? I'll make a note in the docs regardless if you are busy.

Thanks for the notification though, and the compliment!

**Comment by aweber1** [comment]
Ah, sorry if I wasn't clear, I meant that I _had_ to use `"this"` in my existing config otherwise the project didn't work. If I don't use `"this"` it doesn't work. In my case it just wasn't obvious because I was porting my own existing webpack config - not the one from the webpack sample project.

**Comment by pauldotknopf** [comment]
Ah! I see. Ya, I'll make that bit more obvious.
